#!/bin/bash

#加载公共smart函数库
. /var/www/html/vendor/marmot-smart/smartfunc/smartfunc
#加载环境函数库
. /var/www/html/vendor/marmot-smart/smartfunc/environmentfunc
#加载phpfunc,php相关函数库
. /var/www/html/vendor/marmot-smart/smartfunc/phpfunc

case $1 in
'initial') 
	;;
'start')
	environmentStart
	;;
'stop')
	environmentStop
	;;
'upgrade')
	environmentUpgrade
	;;
'cbf')
	cbf
	;;
'composer')
	composer
	;;
'cs')
	cs
	;;
'cpd')
	cpd
	;;
'md')
	md
	;;
'unit')
	unit
	;;
'unitFile')
	unitFile $1
	;;
'unitCover')
	unitCover
	;;
'unitFileCover')
	unitFileCover $1
	;;	
*)
	menu
esac