#!/bin/bash

function checkCommandExecute {
	if [ ! -x $1 ];then 
		chmod +x $1
	fi
}

function cbf {
	checkCommandExecute /var/www/html/vendor/bin/phpcbf
	/var/www/html/vendor/bin/phpcbf
}

function cs {
	checkCommandExecute /var/www/html/vendor/bin/phpcs
	/var/www/html/vendor/bin/phpcs --report-full
}

function composer {
	/usr/local/bin/composer update
}

function cpd {
	checkCommandExecute /var/www/html/vendor/bin/phpcpd
	/var/www/html/vendor/bin/phpcpd --names-exclude src tests
}

function unit {
	checkCommandExecute /var/www/html/vendor/bin/phpunit
	/var/www/html/vendor/bin/phpunit --stop-on-failure
}

function unitFile {
	checkCommandExecute /var/www/html/vendor/bin/phpunit
	/var/www/html/vendor/bin/phpunit --filter="$1"
}

function unitCover {
	checkCommandExecute /var/www/html/vendor/bin/phpunit
	/var/www/html/vendor/bin/phpunit --debug --stop-on-failure --testsuite ut --coverage-html ./docs/UnitTestCover
}

function unitFileCover {
	checkCommandExecute /var/www/html/vendor/bin/phpunit
	/var/www/html/vendor/bin/phpunit --filter="$1" --debug --stop-on-failure --coverage-html ./docs/UnitTestCover
}

function md {
	checkCommandExecute /var/www/html/vendor/bin/phpmd
	/var/www/html/vendor/bin/phpmd ./src,tests text ruleset.xml 
	if [ $? -eq 0 ]
	then
		echo 'check mess complete'
	fi
}
