#!/bin/bash

function checkCommandExecute {
	if [ ! -x ./$1 ];then 
		chmod +x ./$1
	fi
}

function cbf {
	checkCommandExecute ./phpcbf
	./phpcbf
}

function cs {
	checkCommandExecute ./phpcs
	./phpcs --report-full
}

function composer {
	composer update
}

function cpd {
	checkCommandExecute ./cpd
	./phpcpd --names-exclude src tests
}

function unit {
	checkCommandExecute ./phpunit
	./phpunit --stop-on-failure
}

function unitFile {
	checkCommandExecute ./phpunit
	./phpunit --filter="$1"
}

function unitCover {
	checkCommandExecute ./phpunit
	./phpunit --debug --stop-on-failure --testsuite ut --coverage-html ./docs/UnitTestCover
}

function unitFileCover {
	checkCommandExecute ./phpunit
	./phpunit --filter="$1" --debug --stop-on-failure --coverage-html ./docs/UnitTestCoverTemp
}

function md {
	checkCommandExecute ./phpmd
	./phpmd ./src,tests text ruleset.xml 
	if [ $? -eq 0 ]
	then
		echo 'check mess complete'
	fi
}
